### ISSUE TITLE
Criar templates de issues, pull requests e outros

### ISSUE THREAD

**Issue by WelisonR** [fga-eps-mds/EPS-2020-2-G3#1]
## Descrição

A presente issue destina-se a criar templates com o objetivo de facilitar a comunicação dentro do repositório.

## Tarefas

- [x] Criar template de Pull Request;
- [x] Criar template de issues (US);
- [x] Criar template de issues genérico;
- ~~[ ] Criar template de bugs;~~
- [x] Definir labels do repositório.

**Comment by lievertom** [comment]
O template para bugs será feito depois da definição das tecnologias, portanto será aberta uma nova issue.
