### ISSUE TITLE
Colocar um fundo branco na logo do projeto

### ISSUE THREAD

**Issue by Luiz-GL-Campos** [fga-eps-mds/EPS-2020-2-G3#101]
## Descrição

Esta issue têm o objetivo de alterar a base da logo atual, para que o fundo seja um circulo branco dentro da logo e não o atual transparente, pois dificulta a visão da logo em certos casos.

## Tarefas

- [x] Colocar um fundo branco na logo, ao invés do atual que está transparente.
- [x] Aplicar a logo reformulada no README.
- [x] Aplicar a logo reformulada na Wiki e na Documentação.
- [x] Aplicar a logo reformulada no Front End do projeto.

## Critérios de Aceitação

Deve estar corretamente alterada em todos os locais que estão sendo usados a atualmente.

**Comment by laispa** [comment]
## Descrição 
Alteração da logo para fundo branco.
**Resolve a issue [#101]().** 

## Tarefas realizadas


 [ ] Tarefa 1. 

Alteração na Wiki, onde se encontra a imagem
 [ ] Tarefa 2.
