### ISSUE TITLE
[TS03] Melhorar usabilidade das paginas de cadastro, edição e lista de tradução

### ISSUE THREAD

**Issue by andrelucax** [fga-eps-mds/EPS-2020-2-G3#104]
## Descrição

Eu, como **Administrador**, gostaria de conseguir cadastrar, visualizar, editar e excluir palavras e suas respectivas traduções em uma página o mais intuitiva possível pra não necessitar de um treinamento pra conseguir fazer a tarefa.

## Tarefas

- [x] Página de cadastro de palavra
- [x] Página de visualização da lista de palavras
- [x] Página de visualização de uma palavra com seus devidos campos
- [x] Novo formulário para adicionar novas informações em uma palavra cadastrada
- [x] Adicionar as páginas criada as URLs do Django.

## Critérios de Aceitação [?](http://www.metodoagil.com/historias-de-usuario/)

* As páginas criadas devem possuir todos os campos relacionados a tradução de palavra;
* As páginas devem possuir estilização;
* As páginas só devem poder ser acessadas por Administradores;
* As páginas precisam levar em consideração os campos obrigatórios;
* As páginas devem informar o usuário se algum campo estiver errado (antes mesmo do botão enviar);
* Caso um usuário normal acesse a página ele deve ser informado que não possui permissão para ver a mesma;
* Caso o usuário não esteja logado ele deve ser redirecionado a tela de login.

**Comment by WelisonR** [comment]
Issue parcialmente realizada pelas dupla Luiz e Laís (com supervisão do André). Fica pendente para a nova _sprint_ as demais demandas não atendidas pelo PR [#6](https://github.com/fga-eps-mds/2020.2-Projeto-Kokama-Traducao/pull/6).

**Comment by WelisonR** [comment]
Foi criada uma história técnica complementar (#145) à presente TS.
