### ISSUE TITLE
[US10]  Recuperar a senha do administrador 

### ISSUE THREAD

**Issue by laispa** [fga-eps-mds/EPS-2020-2-G3#124]
## Descrição

Eu, [Altaci](https://fga-eps-mds.github.io/2020.2-Projeto-Kokama-Wiki/project/lean-inception/personas/), como administradora, gostaria de recuperar minha senha em caso de perda.

## Tarefas

- [x] Criar página de recuperação de senha ;
- [x] Opção de "esqueci minha senha" na tela de login do administrador.

## Critérios de Aceitação [?](http://www.metodoagil.com/historias-de-usuario/)

- A página de administrador deve ter a opção de recuperar a senha;
- Deve haver algum critério para o administrador conseguir recuperar a sua senha (e-mail, número, etc...);
- Substituição da senha antiga.

## Observações 

- Desenvolvimento em backend.

**Comment by WelisonR** [comment]
Dívida técnica da sprint 10

**Comment by WelisonR** [comment]
Dívida técnica da sprint 11
