### ISSUE TITLE
Automatizar processo de release do projeto

### ISSUE THREAD

**Issue by WelisonR** [fga-eps-mds/EPS-2020-2-G3#125]
## Descrição

Com o objetivo de facilitar o processo de _release_ de versões do projeto, essa tarefa busca automatizar o processo de release e coleta de métricas do sonarcloud.

## Tarefas

- [x] Estudar actions do GitHub actions (ou outras soluções);
- [x] Automatizar o processo de coleta de métricas do projeto;
- [x] Automatizar o processo de releases do projeto.

## Critérios de Aceitação

- Salvar métricas do SonarCloud das _releases_ do projeto;
- Automatizar processo de _release_.

## Observações

- Verificar possibilidades de automatização de _releases_: [exemplo](https://github.com/marketplace/actions/automatic-releases#event-triggers).

**Comment by andrelucax** [comment]
Issue realizada nos repo de traducao e front
