### ISSUE TITLE
Criar ambiente de homologação para o front-end

### ISSUE THREAD

**Issue by WelisonR** [fga-eps-mds/EPS-2020-2-G3#126]
## Descrição

O presente cartão busca criar um canal para entrega contínua de _deploys_ do ambiente de homologação do front-end.

## Tarefas

- [x] Estudar alternativas de implementação do _deploy_ contínuo do front-end;
- [x] Realizar deploy contínuo a partir da _branch dev_;

## Critérios de Aceitação

- Ambiente de homologação do front-end disponível.

## Observações

Estudar documentação do [expo](https://docs.expo.io/distribution/release-channels/) ou outras alternativas.

**Comment by leomedeiros1** [comment]
Ambiente de Homologação disponível [aqui](https://expo.io/@projetokokama/projeto-kokama?release-channel=homolog).
