### ISSUE TITLE
[US19] Tela com informações sobre o projeto

### ISSUE THREAD

**Issue by Luiz-GL-Campos** [fga-eps-mds/EPS-2020-2-G3#141]
## Descrição

Eu [Altaci](https://github.com/fga-eps-mds/2020.2-Projeto-Kokama-Wiki/blob/main/docs/project/lean-inception/personas.md), como administradora, gostaria que um usuário comum possa ver informações sobre o desenvolvimento e toda a equipe envolvida no projeto kokama pelo aplicativo para poder "eternizar" a equipe.

## Tarefas

- [x] Fazer uma parte da navegação do aplicativo para acessar essa tela;
- [ ] Descrição sobre o projeto;
- [x] Cadastrar toda a equipe envolvida com o projeto e suas respectivas informações.

## Critérios de Aceitação [?](http://www.metodoagil.com/historias-de-usuario/)

- Deve seguir o estilo das outras paginas do aplicativo;
- Informação de forma simples e legível;
- Colocar as informações de toda a equipe atualmente envolvida no projeto;
- Realizar testes dos componentes.

## Observações

Algumas navegações para as páginas existentes já estão criadas no arquivo "App.tsx", continuar implementando lá e seguir seu modelo.

## Lembretes 

- Perguntar quais informações devem aparecer nesta tela.

**Comment by WelisonR** [comment]
Dívida da sprint 8.
