### ISSUE TITLE
Configurar integração contínua e deploy contínuo do novo microsserviço de usuário

### ISSUE THREAD

**Issue by WelisonR** [fga-eps-mds/EPS-2020-2-G3#142]
## Descrição

A presente _issue_ busca automatizar o processo de integração contínua e deploy contínuo do novo microsserviço de usuário do Projeto Kokama.

## Tarefas

- [x] Configurar deploy de ambiente de homologação com Heroku (integrado ao cloudinary);
- [x] Configurar análise de código com SonarCloud.

## Critérios de Aceitação

- Deploy do ambiente de homologação disponível para acesso pela _internet_.

**Comment by leomedeiros1** [comment]
Ambiente de Homologação disponível [aqui](https://projeto-kokama-usuario.herokuapp.com/).
