### ISSUE TITLE
Criar landing page para a wiki

### ISSUE THREAD

**Issue by WelisonR** [fga-eps-mds/EPS-2020-2-G3#15]
## Descrição

Criar landing page com a apresentação do projeto, dos membros (EPS e MDS) e dos recursos disponíveis para o usuário navegar (repositórios, wiki).

## Tarefas

- [x] Adicionar imagem ou texto sobre o projeto;
- [x] Colocar informações dos membros de EPS;
- [x] Colocar informações dos membros de MDS;
- [x] Apresentar recursos disponíveis (repositórios).

## Observações

* ~~Salvar foto dos membros na pasta "Integrantes" no Google Drive.~~

**Comment by lievertom** [comment]
não adicionei as fotos dos membros  ao drive, qual o objetivo?

**Comment by WelisonR** [comment]
As fotos no drive seria para fácil acesso pelo time, seja para fazer uma apresentação ou adicionar as fotos dos membros em algum local. Não tem problema.

**Comment by WelisonR** [comment]
Se possível, tente arrumar o bug que impede a visualização da wiki em dispositivos mobile, percebi que o problema acontece no breakpoint de largura 990px.

**Comment by lievertom** [comment]
Vou ajustar o tamanho mínimo da tela para 230px.

**Comment by lievertom** [comment]
O bug foi resolvido
