### ISSUE TITLE
US - História do povo Kokama disponíveis em português e Kokama

### ISSUE THREAD

**Issue by Luiz-GL-Campos** [fga-eps-mds/EPS-2020-2-G3#151]
## Descrição

Eu [Altaci](https://fga-eps-mds.github.io/2020.2-Projeto-Kokama-Wiki/project/lean-inception/personas/), como administradora, gostaria de poder cadastrar as histórias do povo Kokama tanto em Português quanto em Kokama para integrar mais o aplicativo bilíngue e também para que o usuário possa ler tanto na sua língua de origem caso deseje.

## Tarefas

- [x] Adequar protótipo para suportar textos em kokama e português;
- [x] Alterar o backend para possibilitar cardastrar, editar, visualizar e remover as histórias porém em Kokama também (atualmente só é possível cadastrar um tipo de história que está em português).
- [x] No front alterar a parte de histórias para poder ser visualizada em português ou em Kokama se o usuário desejar (implementar um botão que altere a visualização das histórias em português para as histórias em Kokama e vice-versa).
- [x] Implementar a barra de pesquisa na tela de histórias no aplicativo mobile.

## Critérios de Aceitação [?](http://www.metodoagil.com/historias-de-usuario/)

- Seguir o estilo das páginas já feitas tanto no front quanto no back.
- Visualização das histórias em português e kokama na mesma página porém puxando dados diferentes.
- Administradora ser capaz de cadastrar as histórias em português e em kokama no backend.
- Usuário comum ser capaz de visualizar as histórias em português ou em kokama no frontend.
- Ser validado por testes.

## Lembretes

- Fazer um protótipo para ser validado com a professora Altaci.

**Comment by WelisonR** [comment]
Dívida técnica da sprint 9

**Comment by WelisonR** [comment]
Dívida técnica da sprint 11

**Comment by WelisonR** [comment]
Restaram ainda algumas pendências no front-end, que serão resolvidas na presente sprint.

**Comment by Luiz-GL-Campos** [comment]
Pendências cumpridas e funcionalidade 100% entregue.
