### ISSUE TITLE
Interconectar os dockers através de uma network

### ISSUE THREAD

**Issue by WelisonR** [fga-eps-mds/EPS-2020-2-G3#154]
## Descrição

Atualmente, os microsserviços da aplicação, tanto frontend como backend, não estão conversando entre si de maneira adequada, isto é, através de uma _network_. A presente issue busca realizar a interconexão entre os diferentes microsserviços.

## Tarefas

- [ ] Interconectar os dockers através de uma network;
- [ ] Testar requisições entre os microsserviços, inclusive front-end. 

## Critérios de Aceitação

- Requisições entre os microsserviços funcionam corretamente através da rede.

**Comment by leomedeiros1** [comment]
Foi verificado que não há necessidade de uma network para comunicação entre os dockers.
Basta usar `http://SEU_IP_LOCAL:PORTA`  onde `PORTA` referencia a porta mapeada para o docker.
Exemplo: `http://192.168.0.5:8000/admin`
