### ISSUE TITLE
Definir as tecnologias

### ISSUE THREAD

**Issue by andrelucax** [fga-eps-mds/EPS-2020-2-G3#16]
## Descrição

Definir as tecnologias que serão utilizadas na solução do problema.

## Tarefas

- [x] Definir tecnologias para o backend
- [x] Definir tecnologias para o frontend
- [x] Definir banco de dados

**Comment by WelisonR** [comment]
A professora Altaci, na última reunião (26/02), ressaltou um ponto muito importante: alguns alunos dela hoje não conseguem utilizar o aplicativo que está na play store (versão antiga do tradutor kokama), pois o celular não é compatível (usuários ios).

**Comment by WelisonR** [comment]
Tecnologias já consolidadas para o desenvolvimento do projeto.
