### ISSUE TITLE
[TS06] Melhorar a segurança das requisições do backend para o backend

### ISSUE THREAD

**Issue by Luiz-GL-Campos** [fga-eps-mds/EPS-2020-2-G3#161]
## Descrição

Eu [Altaci](https://fga-eps-mds.github.io/2020.2-Projeto-Kokama-Wiki/project/lean-inception/personas/), como administradora, gostaria de proteger os dados dos servidores para que os dados cadastrados não sejam passíveis de alteração ou exclusão por terceiros.

## Tarefas
- [x] As requisições de alteração no banco de dados pelos endpoints só são permitidas para IPs selecionados
- [x] Todas as funcionalidades dos microserviços que dependem de requisições desse microserviço devem continuar funcionando corretamente.

## Critérios de Aceitação [?](http://www.metodoagil.com/historias-de-usuario/)

- A visualização dos dados é pública
- A alteração dos dados é permitida somente pelos super usuários do micro-serviço

**Comment by WelisonR** [comment]
Dívida técnica da sprint 10
