### ISSUE TITLE
[TS07] Testes unitários na tela de tradução do front end (react native)

### ISSUE THREAD

**Issue by luisgaboardi** [fga-eps-mds/EPS-2020-2-G3#162]
## Descrição

Eu, como desenvolvedor, gostaria de que as **funções e os componentes tenham testes unitários** para garantir um maior grau de manutenibilidade e previsibilidade do comportamento da tela de tradução.

## Tarefas

- [x] Fazer testes unitários nas funções usadas na tela de tradução
- [x] Fazer testes unitários nas funções na pasta "/utils"
- [x] Testar os componentes que são visualizados na tela, para promover maior controle do que será ou não renderizado na aplicação.
- [x] Aumentar a cobertura de testes

## Critérios de Aceitação [?](http://www.metodoagil.com/historias-de-usuario/)

- A cobertura dos testes deve ser respectiva ao número de funções e à importância delas, com testes verdadeiramente úteis;
- Os testes devem percorrer o caminho feliz e o triste
- Os limites das funções devem ser testados

## Observações

- Não façam os testes pela quantidade, mas pela qualidade.
- Utilizem do JEST

**Comment by WelisonR** [comment]
Dívida técnica da sprint 10
