### ISSUE TITLE
[TS08] Testes unitários no microsserviço de ensino

### ISSUE THREAD

**Issue by nickby2** [fga-eps-mds/EPS-2020-2-G3#164]
## Descrição

Eu, como desenvolvedor, gostaria de que as **funções e as views tenham testes unitários** para garantir um maior grau de manutenibilidade e previsibilidade do comportamento do microsserviço de ensino.

## Tarefas

- [x] Fazer testes unitários nas funções e views usadas no microsserviço de ensino
- [x] Aumentar a cobertura de testes
- [x] Testar os limites das funções

## Critérios de Aceitação [?](http://www.metodoagil.com/historias-de-usuario/)

- A cobertura dos testes deve ser respectiva ao número de funções e à importância delas, com testes verdadeiramente úteis;
- Os testes devem percorrer o caminho feliz e o triste
- Os limites das funções devem ser testados

**Comment by WelisonR** [comment]
Dívida técnica da sprint 10

**Comment by WelisonR** [comment]
Dívida técnica da sprint 11
