### ISSUE TITLE
[BUG] "sudo make" traducao

### ISSUE THREAD

**Issue by nickby2** [fga-eps-mds/EPS-2020-2-G3#165]
**Descrição do bug**
Quando utilizo o comando "sudo make" no projeto traducao, terminal n roda o código e da um ERROR:

**Passos para reproduzir o bug**
1. Vá para projeto traducao
2. abra o terminal no projeto
3. use o comando sudo make
4. aparece o ERRO:`

![Captura de tela de 2021-04-18 20-48-45](https://user-images.githubusercontent.com/57758405/115166222-6840b680-a088-11eb-8711-8361c15f8e82.png)

**Comportamento esperando**
Uma descrição clara e concisa sobre o que era esperado que acontecesse.

**Screenshots**
Se aplicado, adicionar imagens que ajudem a  @explicar o problema.

**Ambiente**

- SO: 
- Navegador: 
- Docker:
- Docker-compose: 
- Outro: escreva o nome de outros caso necessário

**Contexto adicional**

Prints do error: 

![Captura de tela de 2021-04-18 20-48-45](https://user-images.githubusercontent.com/57758405/115166256-9aeaaf00-a088-11eb-8e29-3721be2855e5.png)
![Captura de tela de 2021-04-18 20-49-03](https://user-images.githubusercontent.com/57758405/115166263-a2aa5380-a088-11eb-99dc-10f2d35b6a5f.png)
![Captura de tela de 2021-04-18 20-49-19](https://user-images.githubusercontent.com/57758405/115166269-ac33bb80-a088-11eb-880d-793a3760c49e.png)
![Captura de tela de 2021-04-18 20-49-27](https://user-images.githubusercontent.com/57758405/115166271-af2eac00-a088-11eb-9237-c3016ed5eccd.png)
![Captura de tela de 2021-04-18 20-49-33](https://user-images.githubusercontent.com/57758405/115166272-b1910600-a088-11eb-8c3b-ec1fb34f2ef1.png)

**Comment by WelisonR** [comment]
@leomedeiros1 Pode verificar o que houve para a gente? Nos logs, percebo um _warning_ relacionado às variáveis de ambiente do banco de dados (postgreSQL). Você está usando corretamente os arquivos `.env`, @nickby2?

Valeu!!

**Comment by andrelucax** [comment]
@nickby2 verifife se seus .env estão de acordo com o env-reference.

Está bem claro o problema que você está tendo nos WARNINGS do primeiro print... Estou deixando essa mensagem e fechando a issue, caso seu problema não seja resolvido pode abrir a issue novamente.

Lembrando que existem 2 .envs, um na raiz do projeto e um no projeto do Django. 
Caso os .env não sejam preenchidos corretamente irá existir uma inconsistência entre as senhas do Banco e gerará erro.

Lembre de Preencher todos os campos do template de bugs também quando o fizer. "Comportamento esperando" e "screenshots" estão com os valores default do template

Abraços
