### ISSUE TITLE
Criar script para automatizar processo de inserção de traduções na base de dados

### ISSUE THREAD

**Issue by WelisonR** [fga-eps-mds/EPS-2020-2-G3#173]
## Descrição

A presente _issue_ tem o objetivo de criar um script que auxilie na extração, transformação e carga de traduções de palavras kokama para português e vice-versa. 

## Tarefas

- [ ] Verificar viabilidade do desenvolvimento do script com base nas planilhas excel disponíveis na pasta `estudo` do drive;
- [ ] Desenvolver script que popule informações das traduções com base no arquivo excel.

## Critérios de Aceitação

- Verificação de viabilidade do desenvolvimento do script; e/ou
- Desenvolvimento do script que popula as traduções na base de dados.

**Comment by andrelucax** [comment]
O CSV disponibilizado não possui um padrão em seus campos além de as frases não adotarem o padrão necessário para correta inserção
