### ISSUE TITLE
[TS11] Testes iniciais no repositório de usuário

### ISSUE THREAD

**Issue by Luiz-GL-Campos** [fga-eps-mds/EPS-2020-2-G3#184]
## Descrição

Eu, como desenvolvedor, gostaria de fazer os testes no repositório de usuário para que tenhamos uma cobertura mais segura do que o código realmente está fazendo.

## Tarefas

- [x] Fazer testes unitários nas funções e views usadas no repositório de usuário;
- [x] Testar os limites das funções e das models.

## Critérios de Aceitação [?](http://www.metodoagil.com/historias-de-usuario/)

- A cobertura dos testes deve ser respectiva ao número de funções e à importância delas, com testes verdadeiramente úteis;
- Os testes devem percorrer o caminho feliz e o triste;
- Os limites das funções devem ser testados.

## Observações 

Usar os testes do repositório de ensino como referência

**Comment by WelisonR** [comment]
A presente issue se propôs a iniciar os testes no microsserviço de usuário. Portanto, as demais pendências serão atendidas em novas TS, em que o foco será a realização de testes nas views de história e de tradução.
