### ISSUE TITLE
Adicionar métrica de testes à análise do SonarCloud

### ISSUE THREAD

**Issue by leomedeiros1** [fga-eps-mds/EPS-2020-2-G3#186]
## Descrição

A presente tarefa busca adicionar a medida de teste aos repositórios.

## Tarefas

- [x] Apresentar badges de testes nos repositórios do projeto;
- [x] Realiza upload dos arquivos de coverage report dos repositórios de backend no Codeclimate;
- [x] Realiza upload dos arquivos de coverage report do repositório de frontend no Codecov;

## Critérios de Aceitação

- SonarCloud gerando arquivo com métrica de testes;
- Informação de cobertura de testes no arquivo `README.md`

**Comment by leomedeiros1** [comment]
Cancelado.

**Comment by WelisonR** [comment]
Reabrindo a tarefa, pois a issue destina-se a apresentar o coverage dos repositórios
