### ISSUE TITLE
Estudo sobre metodologias ágeis

### ISSUE THREAD

**Issue by WelisonR** [fga-eps-mds/EPS-2020-2-G3#25]
## Descrição

Issue criada com a finalidade de difundir conceitos e valores de metodologias ágeis através de materiais de estudo. Tópicos para estudo: Scrum, Extreme Programming, Kanban.

## Tarefas

- [x] Estudar material anexo e outras fontes na área de metodologia ágil;
- [x] Realizar pequeno teste com questões diversificadas sobre metodologias ágeis. ([Link](http://www.quiz-maker.com/Q0Z9P3QLP))

## Critérios de Aceitação

* Todos os membros de MDS responder o pequeno teste sobre metodologias ágeis.

## Recomendação de leitura

* Manifesto ágil: https://www.wikiwand.com/pt/Manifesto_%C3%81gil
* Scrum: https://www.desenvolvimentoagil.com.br/scrum/
* Extreme Programming: https://www.devmedia.com.br/extreme-programming-conceitos-e-praticas/1498
* Kanban: https://blog.runrun.it/o-que-e-kanban/

## Já estudou os tópicos acima?

- [x] Ana
- [x] Fernando
- [x] Lais
- [x] Lucas
- [x] Luís Guilherme
- [x] Luiz Gustavo

**Comment by nickby2** [comment]
gostei muito dos textos, deveria ler lido antes. Muito didáticos ^^

**Comment by WelisonR** [comment]
@SFernandoS Como está o progresso da issue?
