### ISSUE TITLE
Desenvolver primeira versão de rich picture do projeto

### ISSUE THREAD

**Issue by WelisonR** [fga-eps-mds/EPS-2020-2-G3#33]
## Descrição

Desenvolver rich picture com a finalidade de alinhar e expandir pensamentos sobre o projeto

## Tarefas

- [x] Desenvolver rich picture.

### Rich Pictures

- [x] Lucas.
- [x] Luís.

## Critérios de Aceitação

- [x] Validar ao menos um modelo com a professora Altaci (PO).

**Comment by luisgaboardi** [comment]
Obra prima de Lucas e Luís

![Rich Picture 1](https://user-images.githubusercontent.com/45673358/108928175-88bc3980-7620-11eb-9a63-48c1ed6b0182.png)
