### ISSUE TITLE
Desenvolver protótipo de baixa fidelidade

### ISSUE THREAD

**Issue by WelisonR** [fga-eps-mds/EPS-2020-2-G3#35]
## Descrição

Com base na reunião realizada com a PO, desenvolver protótipo de baixa fidelidade para levantar ideias e aspectos visuais de interação que o usuário virá a ter na aplicação.

## Tarefas

- [x] Discutir e desenvolver união do protótipo de baixa fidelidade.

### Protótipos

- [x] Luís e Lucas;
- [x] Laís e Vargas;
- [x] André;
- [x] Lieverton.

## Critérios de Aceitação

- [x] Protótipo em papel ou digital;
- [x] Foco na interação, não no visual;
- [x] Comentar com imagem ou link do protótipo nessa issue.

## Observações

Caso opte por utilizar uma ferramenta digital, segue sugestões:

- MS Paint e derivados;
- [Whimsical](https://whimsical.com/);
- [Figma](https://www.figma.com/)

**Comment by SFernandoS** [comment]
Laís e eu criamos um protótipo de baixa fidelidade que se encontra no drive do Projeto

**Comment by SFernandoS** [comment]
Laís e eu criamos um protótipo de baixa fidelidade que se encontra no drive do Projeto:
[Proposta.pdf](https://github.com/fga-eps-mds/EPS-2020-2-G3/files/6025634/Proposta.pdf)

**Comment by luisgaboardi** [comment]
Eu e o Lucas fizemos dois protótipos de baixa fidelidade:
![Kokama - Baixa Fidelidade](https://user-images.githubusercontent.com/45673358/108790426-70361b80-755b-11eb-907d-c52d3440392d.png)
![Protótipo 2](https://user-images.githubusercontent.com/45673358/108790439-762bfc80-755b-11eb-9b90-f9f21bba41e3.png)

**Comment by lievertom** [comment]
![20210222_214443](https://user-images.githubusercontent.com/31928032/108791938-f30ca580-755e-11eb-86dc-5e5aec5ead6d.jpg)
![20210222_214434](https://user-images.githubusercontent.com/31928032/108791950-facc4a00-755e-11eb-8e68-837a63d3dde6.jpg)

**Comment by andrelucax** [comment]
Segue obra_de_arte.png

![obra_de_arte](https://user-images.githubusercontent.com/42394759/108792257-99f14180-755f-11eb-8bb7-6b61e3c927ad.png)
