### ISSUE TITLE
Criar primeira versão do documento de identidade visual

### ISSUE THREAD

**Issue by WelisonR** [fga-eps-mds/EPS-2020-2-G3#36]
## Descrição

Com base na reunião realizada com a PO, desenvolver a primeira versão do documento de identidade visual, observadas as anotações realizadas no documento de questionário realizado com a professora.

## Tarefas

- [x] Criar primeira versão do documento de identidade visual.

## Critérios de Aceitação

- [x] Validar com a professora Altaci (PO);
- [x] Observar anotações do documento de questionário (relativo a cores, logo).

**Comment by laispa** [comment]
Fernando e eu fizemos até aqui, visto que ainda não foi definido muito bem o protótipo o tópico 2.2 ficou em aberto, e a tipografia foi mais numa fonte geral.
`
[Identidade Visual.pdf](https://github.com/fga-eps-mds/EPS-2020-2-G3/files/6047151/Identidade.Visual.pdf)
`

**Comment by WelisonR** [comment]
Sobre as cores, a professora recomendou a leitura de um TCC que trata sobre o assunto: [Vanessa Porto - TCC](https://bdm.unb.br/bitstream/10483/8651/1/2013_MarjorieAmyYamada_VanessaPorto.pdf).

Sobre a logo, a professora sugeriu que mudássemos o fundo da logo atual ou trabalhássemos em alguma variação (eu sugeriria uma versão digital, feita em svg).

A definição desses tópicos realmente não é tão fácil. Parabéns pelo trabalho, pessoal!! :confetti_ball: :confetti_ball:
