### ISSUE TITLE
Documentar protótipo de média fidelidade

### ISSUE THREAD

**Issue by andrelucax** [fga-eps-mds/EPS-2020-2-G3#37]
## Descrição

Documentar os protótipos desenvolvidos pela equipe junto com a validacao do PO a respeito dos mesmos

## Tarefas

- [x] Uniao do prototipo de baixa fidelidade (prototipo de media fidelidade)

## Critérios de Aceitação

* Os documentos devem conter o autor
* Os documentos devem conter a data
* A validacao do PO deve estar documentada
* Documentar na wiki

## Observações

Os prototipos desenvolvidos pela equipe se encontram no comentario da [issue 35](https://github.com/fga-eps-mds/EPS-2020-2-G3/issues/35)

**Comment by WelisonR** [comment]
Issue destinada à documentação do protótipo de média fidelidade.
