### ISSUE TITLE
Pensar situações, problemas e oportunidades de projeto

### ISSUE THREAD

**Issue by WelisonR** [fga-eps-mds/EPS-2020-2-G3#4]
## Descrição

A presente issue tem por objetivo analisar e escolher com o grupo de MDS e EPS uma situação, problema ou oportunidade de projeto que será desenvolvido pela equipe.

## Tarefas

- [x] Pensar sobre possíveis temas de projeto;
- [x] Documentar ideias de temas de projeto (público-alvo, problemáticas, possíveis soluções, fontes de dados etc);
- [x] Documentar riscos relacionados ao projeto.

## Observações

* Basear-se nos super-temas das issues da disciplina: [MDS/EPS - Issues](https://github.com/fga-eps-mds/A-Disciplina/issues);
* Procurar por fontes de dados que possam ser interessantes a ideia de projeto.

**Comment by WelisonR** [comment]
# Aplicativo voltado para políticas públicas

**1. Principais interessados**:

*   Cidadãos;
*   Setor público.

**2. Objetivo de Desenvolvimento Sustentável, ONU**:

*   ODS16: Paz, justiça e instituições fortes.
  * Desenvolver instituições eficazes, responsáveis e transparentes em todos os níveis.
  * Garantir a tomada de decisão responsiva, inclusiva, participativa e representativa em todos os níveis.

**3. Problemática(s)**:

*   Cidadão não possui participação ativa em reportar problemas em sua cidade ou município;
*   Setor público com grande dificuldade em mapear e priorizar problemas em cidades ou municípios;
*   Setor público não dispõe ao cidadão uma boa solução tecnológica para reportar problemas como:
    *   Falta de energia;
    *   Poda de árvores;
    *   Buracos em rodovias;
    *   Falta de saneamento básico;
    *   Obras deterioradas;
    *   etc.
*   etc.

**4. Propostas iniciais**:

*   **Cidadão reporta em mapa um problema em sua cidade ou município**;
*   **Interação entre cidadãos acerca de um dado problema**;
*   **Disponibilizar informações estratégicas** (em mapa ou relatório) que favoreça políticas públicas;
*   Disponibilizar possibilidade dos órgãos públicos de responder a demandas da sociedade;
etc.

**5. Fonte de dados estratégicos**:

*   **Dataset de acidentes da PRF**:  [Dataset de acidentes PRF](https://www.gov.br/prf/pt-br/acesso-a-informacao/dados-abertos/dados-abertos-acidentes).
    *   Quais os locais com mais acidentes?
    *   Tais acidentes possuem causas naturais (por exemplo, falta de manutenção das rodovias)?
    *   etc.

**Pequeno protótipo de uma ideia de app em raciocínio próximo a proposta acima**: <https://whimsical.com/embed/Y5cMSYte7XQctXcDKKuhdL>.

**Comment by WelisonR** [comment]
-

**Comment by hneri** [comment]
Sobre o tema 1, detalhar a política pública. Genérico para proposição do tema. Está num caminho bom!
Sobre o tema 2, não estou convencido que após a transformação que a sociedade passa, em função do COVID, que um foco na prova física seja adequado, embora a proposta do uso de visão computacional seja bem interessante @WelisonR e demais. Em fim, discutam mais. Deem uma olhada nos quests #1#2#3 do projetão https://www.projetao.com.br/generator/?dun=MetOverview&. Auxiliará vocês nessa etapa.

**Comment by lievertom** [comment]
Sobre o tema 1, foi acordado, entre time, que o foco estaria relacionado à manutenção da estrutura urbana. Os cidadãos poderiam relatar problemas  em rodovias, áreas de convivência, iluminação pública.

**Comment by WelisonR** [comment]
O problema relatado no tema 2 surgiu como oportunidade de implementação em uma empresa de cursinho que opera online, na situação os alunos faziam simulados impressos e precisavam colocar os gabaritos no sistema para correção e geração de resultado, à época optou-se pelo método mais barato que seria o preenchimento manual das respostas no sistema por parte do usuário. Então, além da oportunidade de aplicação no ambiente presencial, há a possibilidade de utilizar esse recurso em ambientes que operam de modo online, visto que os métodos de correção virtual e de correção automatizada de folhas de gabarito com visão computacional podem ser complementares.

**Comment by hneri** [comment]
Entendi @lievertom e demais. Nesse sentido, e considerando a definição do problema relatado no tema 1 já existem diferentes soluções, inclusive em semestres anteriores da disciplina. Ou seja, a sentença de proposição do problema de vocês não se confirma. Considerando apenas a proposta de solução, já existem produtos disponíveis. E especificamento sobre a proposta de solução qual seria a inovação que o produto de vocês traria? **Exemplos** de soluções já existentes:
- https://www.colab.re/
- https://new.voltaredonda.rj.gov.br/todas-as-noticias/27-seplag/818-fiscaliza-vr-facilita-atendimento-ao-cidad%C3%A3o
- https://play.google.com/store/apps/details?id=br.gov.go.goiania.outprod01.novoprefeitura24horas&hl=pt_BR&gl=US
- https://play.google.com/store/apps/details?id=br.gov.mpdg.siconvfiscalizacao&hl=pt

**Comment by hneri** [comment]
@WelisonR e demais, parece-me que o problema definido por vocês não seja exatamente um problema:
- http://hsinformatica.com.br/Formul%C3%A1rios_Gabaritos_de_Prova.html?gclid=Cj0KCQiAyJOBBhDCARIsAJG2h5eZOCqMoEGgzDVV-SznZMBOvpF2YjdZvk5P8oo5NeYzOaqKeNXN8pMaAjZYEALw_wcB
- https://www.minhaprova.com.br/
- https://escolaweb.com.br/blog/corretor-de-provas/
- https://www.zoomeduca.com.br/
- https://blog.meritt.com.br/voce-sabia-camera-de-seu-celular-pode-ser-um-leitor-de-gabarito/
- https://olimpiada.ic.unicamp.br/sisca/corretor
- https://remarkoffice.com.br/tag/corretor-de-provas/

**Comment by WelisonR** [comment]
Sobre o tema 2, indo um pouco além nessa pesquisa de mercado, podemos constatar os seguintes fatos:

1. Com exceção do Sisca, corretor desenvolvido pela OBI, todos os demais sistemas listados são pagos;
2. Nenhuma solução testada possui código-fonte aberto ou de fácil acesso;
3. Aplicações gratuitas encontradas não funcionam bem;
4. Não há como ponderar questões nos sistemas;
5. As aplicações testadas trabalham apenas com o sistema de múltipla-escolha, não há questões:
   1. binárias;
   2. dissertativas.
6. As aplicações testadas não se mostram completas no sentido de ter simultaneamente:
   1. gratuidade;
   2. personalização de gabaritos;
   3. banco de questões;
   4. possibilidade de realizar provas online ou presencial (com uso de correção automatizada);
   5. fornecer dados ao estudante de seu desempenho nas disciplinas ao longo do tempo;
   6. relatórios diversos relacionados a provas e a turma.

A aplicação que mais se assemelhou a nossa ideia é a minhaprova, que possui as seguintes características:

*   Serviço pago:
    *   Valor fixo + acréscimo por correção + acréscimo por aluno + acréscimo por professor (depende do plano);
    *   Muitas limitações no plano mais básico.
*   Se aplicam ao minhaprova os itens 1, 2, 4, 5, 6 (possui 6.2 e 6.6 apenas).

Nesse sentido, é possível notar que tais sistemas ou não são acessíveis (monetariamente ou funcionalmente) ou não são completos o suficiente (nem adaptáveis), então enxergamos a possibilidade de trabalhar nesse tema de forma a fornecer uma solução que utiliza PWA e que tenha como diferencial os recursos não abrangidos pelos concorrentes, conforme exposto em alguns exemplos acima.

**Comment by hneri** [comment]
@WelisonR e demais  o foco de vocês está na visão do produto e não no tema-problema. Vou levar essa "thread" de discussão para o discord do time e continuamos por lá.

**Comment by andrelucax** [comment]
Issue resolvida via conversa no Discord.
