### ISSUE TITLE
Aplicar identidade visual na wiki

### ISSUE THREAD

**Issue by WelisonR** [fga-eps-mds/EPS-2020-2-G3#50]
## Descrição

A presente issue tem o objetivo de aplicar a identidade visual, definida em outra issue, na wiki do projeto.

## Tarefas

- [x] Adicionar logo e nome do projeto, conforme exemplo 1. Observação: já existe o código (está comentado), seria gerar a imagem e substituir o link.
- [x] Adicionar logo e nome do projeto na navbar da landing page (deve estar bem visível);
- [x] Atualizar papel dos membros de EPS na landing page;
- [x] Aplicar na landing page as cores definidas na identidade visual ;
- [x] Adicionar logo, nome e descrição do projeto em todos os atributos aplicáveis no arquivo `mkdocs.yml`;
- [x] Alterar cores do mkdocs-material de acordo com a identidade visual;
- [x] Outras personalizações (opcional).

## Critérios de Aceitação

- Seguir identidade visual da aplicação.

### Exemplo 1

![Exemplo - mia ajuda](https://user-images.githubusercontent.com/31112450/109433290-69d9f080-79ee-11eb-93e9-92fce078f06a.png)

**Comment by lievertom** [comment]
Lembrem-se que é necessário esperar a validação da logo para adicioná-la à página .

**Comment by Luiz-GL-Campos** [comment]
![README](https://user-images.githubusercontent.com/42492795/110050548-e2b0b380-7d32-11eb-8722-de1a0efb71a3.PNG)
Imagem da logo no README

**Comment by nickby2** [comment]
![Captura de tela de 2021-03-04 21-45-50](https://user-images.githubusercontent.com/57758405/110051146-10e2c300-7d34-11eb-83fa-65ee6fe26280.png)
![Captura de tela de 2021-03-04 21-47-58](https://user-images.githubusercontent.com/57758405/110051153-13451d00-7d34-11eb-99f6-9f5d4ed4cfba.png)

Resolve:
- Adicionar logo e nome do projeto na navbar da landing page (deve estar bem visível);
- Atualizar papel dos membros de EPS na landing page;
- Aplicar na landing page as cores definidas na identidade visual ;
- Adicionar logo, nome e descrição do projeto em todos os atributos aplicáveis no arquivo mkdocs.yml;
- Alterar cores do mkdocs-material de acordo com a identidade visual;
