### ISSUE TITLE
Estudar react native

### ISSUE THREAD

**Issue by WelisonR** [fga-eps-mds/EPS-2020-2-G3#56]
## Descrição

Realizar dojo de react native com a equipe de forma a apresentar os principais conceitos da tecnologia.

## Tarefas

- [x] Conceitos gerais sobre aplicação react;
- [x] Hierarquia (organização) em uma aplicação react native;
- [x] Componentização;
- [x] Typescript + React;
- [x] JSX;
- [x] Context API;
- [x] Uso dos principais hooks (useState, useEffect);
- [x] Uso de props, prop drilling;
- [x] Estilização em react;
- [x] Outros.

## Critérios de Aceitação

- Realizar treinamento com a equipe.

## Documentações

* React Native: https://reactnative.dev/
* React: https://pt-br.reactjs.org/

**Comment by WelisonR** [comment]
@nickby2 @laispa @luisgaboardi @LightZX @SFernandoS @aluzianobriceno Por favor, já iniciar os estudos em react native, principalmente sobre os tópicos listados acima. Recomendo utilizarem o expo por conta da facilidade de desenvolvimento.

**Comment by luisgaboardi** [comment]
Uma sugestão para quando for uma Issue de estudo: fazer um checkbox pra cada um dos MDS, pra a gente ter um controle

**Comment by WelisonR** [comment]
@luisgaboardi Agradeço!

Adicionada a checkbox, fiquem à vontade para marcá-la após estudar o conteúdo proposto

**Comment by WelisonR** [comment]
Issue redefinida de dojo para estudos.
