### ISSUE TITLE
Estudar backend (django)

### ISSUE THREAD

**Issue by WelisonR** [fga-eps-mds/EPS-2020-2-G3#57]
## Descrição

_Issue_ destinada a trabalhar conceitos relacionados a banco de dados e desenvolvimento _backend_ com django, com a finalidade de tornar tais conceitos mais fáceis aos membros da equipe.

## Tarefas

- [x] Explorar a teoria básica de banco de dados (modelagem);
- [x] Explorar o básico sobre SQL;
- [x] Explorar sobre conceitos e estrutura de aplicações backend (Django);
- [x] Explorar CRUD básico em django.

## Critérios de Aceitação

- [x] Utilizar banco de dados relacional postgreSQL.

**Comment by WelisonR** [comment]
@nickby2 @laispa @luisgaboardi @LightZX @SFernandoS @aluzianobriceno Por favor, já iniciar os estudos em backend, principalmente sobre os tópicos listados acima.

**Comment by andrelucax** [comment]
@WelisonR concordo que vale a pena levantaar pontos sobre banco, modelagem, etc mas não vejo a necessidade de utilizar o postgreSQL no dojo do backend, só vai subir um pouco a complexidade e não vai agregar ensinar a mudar o banco do django. O padrão do Django é SQLite que é bem leve e completo. Para produção talvez mudemos o padrão do Django, mas para um dojo e treinamento não vale a pena pois que não faça tanta diferença assim pq ele faz "a magica" pra gente. E fica de pesquisa futura pra eles fazerem quando formos mudar para um banco em produção

**Comment by WelisonR** [comment]
@andrelucax Concordo, André, pode ser utilizado um banco de dados mais simples, como o SQLite. Na documentação oficial do Docker tem um exemplo de configuração do Django com o postgres, talvez gerar esse boilerplate ou indicar que eles sigam o tutorial possa ser uma outra solução: https://docs.docker.com/compose/django/. Deixo a decisão com vocês.

Valeu!!

**Comment by WelisonR** [comment]
Issue redefinida de dojo para estudos. Especificar melhor os tópicos que deverão ser estudados em relação ao backend. @andrelucax @leomedeiros1
