### ISSUE TITLE
Criar documento de planejamento da sprint 4

### ISSUE THREAD

**Issue by leomedeiros1** [fga-eps-mds/EPS-2020-2-G3#69]
## Descrição

Issue destinada a documentar o planejamento da sprint 4 na wiki

## Tarefas

- [ ] Documentar atividades desenvolvidas;
- [ ] Documentar papéis desempenhos por membros da equipe;
- [ ] Documentar pareamentos.

## Critérios de Aceitação

- [ ] Documentar na wiki

**Comment by WelisonR** [comment]
@leomedeiros1, troquei o assign porque pretendo gerar o documento dessa issue com a automação proposta em #81. Adicionei você em outra issue
