### ISSUE TITLE
Criar quadro de conhecimentos da equipe (inicial)

### ISSUE THREAD

**Issue by WelisonR** [fga-eps-mds/EPS-2020-2-G3#7]
## Descrição

Elaborar planilha com quadro de conhecimentos da equipe com o objetivo de entender as áreas de conhecimento de cada membro da equipe.

## Tarefas

- [x] Elaborar planilha com quadro de conhecimentos de programação e gerência.

## Observações

* A planilha será preenchida por todos os membros.

**Comment by lievertom** [comment]
![Quadro de conhecimento](https://user-images.githubusercontent.com/31112450/107518566-ed41b800-6b8d-11eb-9d8d-ed470deca7e5.png)


A planilha foi preenchida na reunião inicial com todos os integrantes da equipe no dia 06 de fevereiro de 2020.

**Comment by WelisonR** [comment]
Documentação na wiki será feita em tarefa posterior.
