### ISSUE TITLE
Criar repositórios do projeto na organização da disciplina

### ISSUE THREAD

**Issue by WelisonR** [fga-eps-mds/EPS-2020-2-G3#73]
## Descrição

Issue destinada a criação dos repositórios do frontend e do backend na organização fga-eps-mds.

## Tarefas

- [x] Criar repositórios dos microsserviços do backend;
- [x] Criar repositório do frontend.

## Critérios de Aceitação

- Repositórios devem ter sido criados dentro da organização da disciplina;
- Nome e descrição do repositório coerentes.

**Comment by lievertom** [comment]
Foram criados mais três repositórios para o Projeto Kokama, sendo eles [2020.2-Projeto-Kokama-Traducao](https://github.com/fga-eps-mds/2020.2-Projeto-Kokama-Traducao), [2020.2-Projeto-Kokama-Ensino](https://github.com/fga-eps-mds/2020.2-Projeto-Kokama-Ensino) e [2020.2-Projeto-Kokama-Frond-end](https://github.com/fga-eps-mds/2020.2-Projeto-Kokama-Front-end).
