### ISSUE TITLE
Configurar repositórios do backend

### ISSUE THREAD

**Issue by WelisonR** [fga-eps-mds/EPS-2020-2-G3#74]
## Descrição

Iniciada as etapas relacionadas ao desenvolvimento da aplicação, torna-se essencial ter um ambiente estável para que a equipe de desenvolvimento possa trabalhar da melhor maneira possível. Nesse sentido, essa issue destina-se a criar ambientes containerizados a fim de facilitar o processo de desenvolvimento.

## Tarefas

Para cada microsserviço do backend, criar o boilerplate:

- [x] Adicionar serviço do framework django ao docker-compose;
- [x] Adicionar serviço de banco de dados postgreSQL ao docker-compose;
- [x] Iniciar uma aplicação padrão django.

## Critérios de Aceitação

- Membros da equipe devem conseguir utilizar o ambiente de desenvolvimento construído.

**Comment by leomedeiros1** [comment]
Repositórios criados e configurados! [Tradução](https://github.com/fga-eps-mds/2020.2-Projeto-Kokama-Traducao) e [Ensino](https://github.com/fga-eps-mds/2020.2-Projeto-Kokama-Ensino)
