### ISSUE TITLE
Configurar repositório do frontend

### ISSUE THREAD

**Issue by WelisonR** [fga-eps-mds/EPS-2020-2-G3#75]
## Descrição

Iniciada as etapas relacionadas ao desenvolvimento da aplicação, torna-se essencial ter um ambiente estável para que a equipe de desenvolvimento possa trabalhar da melhor maneira possível. Nesse sentido, essa issue destina-se a criar ambientes containerizados a fim de facilitar o processo de desenvolvimento.

## Tarefas

- [x] Avaliar complexidade e necessidade de docker no front;
- [x] Se aplicável, adicionar serviço da aplicação react native (expo) ao docker-compose;
- [x] Iniciar uma aplicação padrão expo - react native que suporte typescript.

## Critérios de Aceitação

- Membros da equipe devem conseguir utilizar o ambiente de desenvolvimento construído.

**Comment by leomedeiros1** [comment]
Repositório criado e configurado! [Front-end](https://github.com/fga-eps-mds/2020.2-Projeto-Kokama-Front-end)
