### ISSUE TITLE
[BUG] Erro ao rodar o docker do backend

### ISSUE THREAD

**Issue by andrelucax** [fga-eps-mds/EPS-2020-2-G3#91]
## Comportamento esperado

Docker subisse o servidor

## Comportamento encontrado

Erro de sincronização do container do banco com o container do backend.

## Erro

<details>
<summary>Erro completo (terminal)</summary>
andrelucax : fox  ➜  2020.2-Projeto-Kokama-Traducao git:(dev) ✗ sudo docker-compose up  

Creating network "20202-projeto-kokama-traducao_default" with the default driver

Creating translate-db ... done

Creating translate-microservice ... done

Attaching to translate-db, translate-microservice

translate-db | The files belonging to this database system will be owned by user "postgres".

translate-db | This user must also own the server process.

translate-db | 

translate-db | The database cluster will be initialized with locale "en_US.utf8".

translate-db | The default database encoding has accordingly been set to "UTF8".

translate-db | The default text search configuration will be set to "english".

translate-db | 

translate-db | Data page checksums are disabled.

translate-db | 

translate-db | fixing permissions on existing directory /var/lib/postgresql/data ... ok

translate-db | creating subdirectories ... ok

translate-db | selecting dynamic shared memory implementation ... posix

translate-db | selecting default max_connections ... 100

translate-db | selecting default shared_buffers ... 128MB

translate-db | selecting default time zone ... Etc/UTC

translate-db | creating configuration files ... ok

translate-db | running bootstrap script ... ok

translate-db | performing post-bootstrap initialization ... ok

translate-db | syncing data to disk ... ok

translate-db | 

translate-db | 

translate-db | Success. You can now start the database server using:

translate-db | 

translate-db |     pg_ctl -D /var/lib/postgresql/data -l logfile start

translate-db | 

translate-db | initdb: warning: enabling "trust" authentication for local connections

translate-db | You can change this by editing pg_hba.conf or using the option -A, or

translate-db | --auth-local and --auth-host, the next time you run initdb.

translate-db | waiting for server to start....2021-03-09 21:57:22.771 UTC [46] LOG:  starting PostgreSQL 13.2 (Debian 13.2-
1.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit
translate-db | 2021-03-09 21:57:23.050 UTC [46] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"

translate-db | 2021-03-09 21:57:23.551 UTC [47] LOG:  database system was shut down at 2021-03-09 21:57:19 UTC

translate-db | 2021-03-09 21:57:23.670 UTC [46] LOG:  database system is ready to accept connections

translate-db |  done

translate-db | server started

translate-db | 

translate-db | /usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*

translate-db | 

translate-db | 2021-03-09 21:57:23.736 UTC [46] LOG:  received fast shutdown request

translate-db | waiting for server to shut down....2021-03-09 21:57:23.773 UTC [46] LOG:  aborting any active transactions

translate-db | 2021-03-09 21:57:23.775 UTC [46] LOG:  background worker "logical replication launcher" (PID 53) exited with 
exit code 1
translate-db | 2021-03-09 21:57:23.775 UTC [48] LOG:  shutting down

translate-db | 2021-03-09 21:57:24.131 UTC [46] LOG:  database system is shut down

translate-db |  done

translate-db | server stopped

translate-db | 

translate-db | PostgreSQL init process complete; ready for start up.

translate-db | 

translate-microservice | Watching for file changes with StatReloader

translate-microservice | Performing system checks...

translate-microservice | 

translate-microservice | System check identified no issues (0 silenced).

translate-db | 2021-03-09 21:57:24.204 UTC [1] LOG:  starting PostgreSQL 13.2 (Debian 13.2-1.pgdg100+1) on x86_64-pc-
linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit
translate-db | 2021-03-09 21:57:24.205 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432

translate-db | 2021-03-09 21:57:24.205 UTC [1] LOG:  listening on IPv6 address "::", port 5432

translate-db | 2021-03-09 21:57:24.289 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"

translate-db | 2021-03-09 21:57:24.349 UTC [65] LOG:  database system was shut down at 2021-03-09 21:57:24 UTC

translate-db | 2021-03-09 21:57:24.349 UTC [66] FATAL:  the database system is starting up

translate-microservice | Exception in thread django-main-thread:

translate-microservice | Traceback (most recent call last):

translate-microservice |   File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 219, in 
ensure_connection
translate-microservice |     self.connect()

translate-microservice |   File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner

translate-microservice |     return func(*args, **kwargs)

translate-microservice |   File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 200, in connect

translate-microservice |     self.connection = self.get_new_connection(conn_params)

translate-microservice |   File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner

translate-microservice |     return func(*args, **kwargs)

translate-microservice |   File "/usr/local/lib/python3.9/site-packages/django/db/backends/postgresql/base.py", line 187, in 
get_new_connection
translate-microservice |     connection = Database.connect(**conn_params)

translate-microservice |   File "/usr/local/lib/python3.9/site-packages/psycopg2/__init__.py", line 127, in connect

translate-microservice |     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)

translate-microservice | psycopg2.OperationalError: FATAL:  the database system is starting up

translate-microservice | 

translate-microservice | 

translate-microservice | The above exception was the direct cause of the following exception:

translate-microservice | 

translate-microservice | Traceback (most recent call last):

translate-microservice |   File "/usr/local/lib/python3.9/threading.py", line 954, in _bootstrap_inner

translate-microservice |     self.run()

translate-microservice |   File "/usr/local/lib/python3.9/threading.py", line 892, in run

translate-microservice |     self._target(*self._args, **self._kwargs)

translate-microservice |   File "/usr/local/lib/python3.9/site-packages/django/utils/autoreload.py", line 53, in wrapper

translate-microservice |     fn(*args, **kwargs)

translate-microservice |   File "/usr/local/lib/python3.9/site-packages/django/core/management/commands/runserver.py", line 
121, in inner_run
translate-microservice |     self.check_migrations()

translate-microservice |   File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 459, in 
check_migrations
translate-microservice |     executor = MigrationExecutor(connections[DEFAULT_DB_ALIAS])

translate-microservice |   File "/usr/local/lib/python3.9/site-packages/django/db/migrations/executor.py", line 18, in __init__

translate-microservice |     self.loader = MigrationLoader(self.connection)

translate-microservice |   File "/usr/local/lib/python3.9/site-packages/django/db/migrations/loader.py", line 53, in __init__

translate-microservice |     self.build_graph()

translate-microservice |   File "/usr/local/lib/python3.9/site-packages/django/db/migrations/loader.py", line 216, in build_graph

translate-microservice |     self.applied_migrations = recorder.applied_migrations()

translate-microservice |   File "/usr/local/lib/python3.9/site-packages/django/db/migrations/recorder.py", line 77, in 
applied_migrations
translate-microservice |     if self.has_table():

translate-microservice |   File "/usr/local/lib/python3.9/site-packages/django/db/migrations/recorder.py", line 55, in has_table

translate-microservice |     with self.connection.cursor() as cursor:

translate-microservice |   File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner

translate-microservice |     return func(*args, **kwargs)

translate-microservice |   File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 259, in cursor

translate-microservice |     return self._cursor()

translate-microservice |   File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 235, in _cursor

translate-microservice |     self.ensure_connection()

translate-microservice |   File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner

translate-microservice |     return func(*args, **kwargs)

translate-microservice |   File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 219, in 
ensure_connection
translate-microservice |     self.connect()

translate-microservice |   File "/usr/local/lib/python3.9/site-packages/django/db/utils.py", line 90, in __exit__

translate-microservice |     raise dj_exc_value.with_traceback(traceback) from exc_value

translate-microservice |   File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 219, in 
ensure_connection
translate-microservice |     self.connect()

translate-microservice |   File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner

translate-microservice |     return func(*args, **kwargs)

translate-microservice |   File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 200, in connect

translate-microservice |     self.connection = self.get_new_connection(conn_params)

translate-microservice |   File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner

translate-microservice |     return func(*args, **kwargs)

translate-microservice |   File "/usr/local/lib/python3.9/site-packages/django/db/backends/postgresql/base.py", line 187, in 
get_new_connection
translate-microservice |     connection = Database.connect(**conn_params)

translate-microservice |   File "/usr/local/lib/python3.9/site-packages/psycopg2/__init__.py", line 127, in connect

translate-microservice |     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)

translate-microservice | django.db.utils.OperationalError: FATAL:  the database system is starting up

translate-microservice | 

translate-db | 2021-03-09 21:57:24.401 UTC [1] LOG:  database system is ready to accept connections

</details>

Aparentemente o banco precisar dar down e up novamente e só o depends_on nao resolve o problema

**Comment by leomedeiros1** [comment]
Foram feitas as devidas correções em ambos os repositórios de Back-end.
