### ISSUE TITLE
Configurar ferramenta SonarQube nos repositórios

### ISSUE THREAD

**Issue by WelisonR** [fga-eps-mds/EPS-2020-2-G3#92]
## Descrição

Com o objetivo de melhorar a qualidade de código e de produto da solução de software desenvolvida pela equipe, a atual issue destina-se a realizar as configurações inicias da ferramenta [SonarQube](https://www.sonarqube.org/).

## Tarefas

- [x] Configurar SonarQube no microserviço de tradução;
- [x] Configurar SonarQube no microserviço de ensino;
- [x] Configurar SonarQube no frontend.

## Critérios de Aceitação

- Ambiente no SonarQube configurado adequadamente;
- Membros da equipe conseguem visualizar e utilizar recursos do SonarQube.

**Comment by andrelucax** [comment]
Adicionei o sonarcloud nos 3 repositorios, coloquei no readme ja
