### ISSUE TITLE
[US04] Inserção de caracter especial

### ISSUE THREAD

**Issue by luisgaboardi** [fga-eps-mds/EPS-2020-2-G3#93]
## Descrição

Eu, [Idiosmar](https://fga-eps-mds.github.io/2020.2-Projeto-Kokama-Wiki/project/lean-inception/personas/), como **usuário**, gostaria de **inserir o caractere especial da gramática Kokama** que não possuo no teclado do meu celular **na barra de pesquisa** da tradução de palavra.

## Tarefas

- [x] Possibilitar pesquisar palavras que possuem o caractere especial da gramática Kokama. 

## Critérios de Aceitação [?](http://www.metodoagil.com/historias-de-usuario/)

- Deve ser possível pesquisar palavras que tenham um caractere especial que não existe no teclado Português Brasileiro;

## Observações

- A atividade em questão envolve apenas desenvolvimento em frontend.

**Comment by Luiz-GL-Campos** [comment]
![Botão ɨ](https://user-images.githubusercontent.com/42492795/111715669-16133800-8833-11eb-8e4c-d7f3a5c57a32.PNG)
Desenvolvimento até o dia 18/03/2021 - Implementação funcional, mas melhorias em progresso.
