### ISSUE TITLE
[US06] Atualizar dicionário de palavras

### ISSUE THREAD

**Issue by Luiz-GL-Campos** [fga-eps-mds/EPS-2020-2-G3#94]
## Descrição

Eu, [Idiosmar](https://fga-eps-mds.github.io/2020.2-Projeto-Kokama-Wiki/project/lean-inception/personas/), como **usuário**, gostaria de **ter as palavras da língua Kokama atualizadas junto as suas respectivas traduções em Português, além de frases de exemplo e falas(masculino e feminino)** para que **sempre mantenha meu aplicativo a par com as atualizações de palavras mais recentes**.

## Tarefas

- [x] Possibilitar atualização dos dados do dicionário no aplicativo.
- [x] A importação do dicionário deve ser global. A aplicação inteira deve ter acesso à ele.
- [x] Modificar o arquivo JSON (que representa o dicionário) no projeto do React-Native para ser compatível com o modelo atual de dicionário/palavra no banco de dados.

## Critérios de Aceitação [?](http://www.metodoagil.com/historias-de-usuario/)

- As tarefas acima serão executadas automaticamente (sem intervenção do usuário);
- Deve-se utilizar recursos do React Native, tal como o storage e Context API para realizar as atividades propostas

## Observações 

 - A atualização pode ser feita uma vez ao dia.
 - A atividade em questão envolve apenas desenvolvimento em Back-end no dispositivo do usuário.

**Comment by WelisonR** [comment]
Dívida técnica para a sprint 6.
