### ISSUE TITLE
[US05] Histórico de palavras pesquisadas

### ISSUE THREAD

**Issue by aluzianobriceno** [fga-eps-mds/EPS-2020-2-G3#95]
## Descrição

Eu, [Archimedes](https://fga-eps-mds.github.io/2020.2-Projeto-Kokama-Wiki/project/lean-inception/personas/), como **usuário**, gostaria de **ver o meu histórico de palavras traduzidas** para **saber quais palavras eu já pesquisei**.

## Tarefas

- [x] Visualização das últimas 10 palavras traduzidas
- [x] Para cada palavra no histórico, visualizar em Português e em Kokama
- [x] Utilizar o respectivo componente do React Native para o histórico ser um dropdown
- [x] Ao clicar na palavra no histórico, apresentar a tradução dela como se o usuário tivesse a digitado na pesquisa
- [x] Armazenado do histórico no aparelho celular através de storage.

## Critérios de Aceitação [?](http://www.metodoagil.com/historias-de-usuario/)

- Fácil acesso ao histórico de palavras já pesquisadas.
- O histórico das últimas palavras deve persistir no aparelho do usuário.
- O histórico está devidamente estilizado e condizente com a identidade visual do projeto.
- O usuário pode usar o histórico como um atalho para pesquisar a tradução de uma palavra traduzida recentemente.

## Observações 

- A atividade em questão envolve apenas desenvolvimento em Front-End.
- O prazo para a sua finalização é a Release 1

**Comment by WelisonR** [comment]
Dívida técnica para a sprint 6.
